### PR TITLE
Update kab.txt

### PR DESCRIPTION
**Pull request by BoFFire**
Hi,

Here is a list of Kabyle words made by the Fourth Amazigh language district teachers and students - Tizi Ouzou, Algeria.

The list was collected by @ZiriSut and organized then shuffled by me.

Total : 1442 entries covering nearly all the Kabyle alphabet, with some exceptions only.

All the credits go to these teachers an students :)

### CODE REVIEW

**Comment by bragefuglseth** [comment]
Great! Thanks!

**Comment by bragefuglseth** [comment]
I'd like to credit the students/district/university somehow in the Orthography section of the about window, along with the other people who have made linguistic contributions to Keypunch. Do you have a suggestion for a short phrase to do this? (e.g. "Students of X university" or "X university district")

**Comment by BoFFire** [comment]
May be Students of Tizi-Ouzou university will be OK.

**Comment by ZiriSut** [comment]
Hi!
These are primary school Tamazight teachers, not university students.

**Comment by bragefuglseth** [comment]
Thanks for the correction! Will fix it ASAP.

**Pull request merged**
