### PR TITLE
Added Bulgarian UI translation

### PR DESCRIPTION
**Pull request by twlvnn**
This pull request contains the Bulgarian UI translation for keypunch. Please double-check if I added the language to the build process correctly to be sure.

### CODE REVIEW

**Comment by bragefuglseth** [comment]
On the technical side of things this is good to go. I'll wait for a response to @UrtsiSantsi's suggestion before merging :slightly_smiling_face:

**Comment by twlvnn** [comment]
Thanks for the feedback UrtsiSantsi! I try to reuse translations from other apps as much as I can so its consistent and the functionality is easier to grasp between the apps. "друг/о" uses fewer letters causing less visual problems in the UI due to length and it also has more uses from other apps than "по избор" in the GNOME ecosystem from what I gather. The pangram I picked is the one I personally liked, but I also like that the one you mentioned has the country in it which might be cooler to see for the first time when you open that page so I will change it for you!

**Comment by twlvnn** [comment]
I took a look at occurances in other apps and I saw "По избор" used in gimp for "custom" and sometimes used for "друг/о" in GTK, deluge and others. In my notes I have "по избор" as a preferred translation for the word "optional"  but I think you're right that its also applicable here.

I notice this happening with a lot of apps in GNOME/open source where its hard to find a consistent word for some terms in Bulgarian, so I prioritize that choice first by what GNOME's translation coordinator recommends me to use, and second by most occurances which I can get by using grep on every po file available in GNOME. And we can always change it in the future so I'm totally fine with that if we decide its better to do so for everyone!

**Comment by bragefuglseth** [comment]
Great!

**Pull request merged**
